In [3]:
import pandas as pd
import numpy as np

In [ ]:
df1 = pd.read_csv('data/to_use/participant_info.csv', encoding='utf-8-sig')
df2 = pd.read_csv('data/processed/surveys.csv', encoding='utf-8-sig')

/Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/lib/ipykernel/py3/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]
<positron-console-cell-28>:3: DtypeWarning: Columns (0: Date.DeEnrolled, 1: Special.Project) have mixed types. Specify dtype option on import or set low_memory=False.

/Users/sonia/Documents/SYEP

<positron-console-cell-28>:4: DtypeWarning: Columns (0: Through which organization are you participating in the SYEP program?, 1: Through which organization are you participating in the SYEP program? - Other/I don't know: (Please fill in), 2: How old are you?, 3: How did you hear about this SYEP program? [Choose one answer], 4: How did you hear about this SYEP program? [Choose one answer] - Other (please specify), 5: What would you have done this summer if you had not been in SYEP? [Check all that apply] - None of the above, 6: What would you have done this summer if you had not been in SYEP? [Check all that apply] - A different part-time job, 7: What would you have done this summer if you had not been in SYEP? [Check all that apply] - A different full-time job, 8: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Volunteered, 9: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Paid summer internship, 10: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Unpaid summer internship, 11: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Summer camp, 12: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Summer school, 13: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Spending time with friends, 14: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Spending time with family, 15: What would you have done this summer if you had not been in SYEP? [Check all that apply] - I had no other summer plans, 16: Please indicate which of the following statements you agree with. [Check all that apply] - None of the above, 17: Please indicate which of the following statements you agree with. [Check all that apply] - SYEP was my first choice for a summer program this year , 18: Please indicate which of the following statements you agree with. [Check all that apply] - I understood all the steps I needed to complete to apply and enroll to the program , 19: Please indicate which of the following statements you agree with. [Check all that apply] - I was able to get the information I needed to apply quickly and easily , 20: Please indicate which of the following statements you agree with. [Check all that apply] - When I started this program, I had a good idea of what it would be like , 21: Please indicate which of the following statements you agree with. [Check all that apply] - I understand how to earn the full payment amount, 22: Please indicate which of the following statements you agree with. [Check all that apply] - I understand the steps I need to take to receive my payment , 23: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Learn more about career options, 24: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Earn money, 25: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Meet new people while participating in the programming, 26: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Find a summer job or internship, 27: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Learn new skills, 28: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Receive work readiness training, 29: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Have safe and productive activity this summer, 30: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - To earn course credit, 31: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Other (please specify), 32: How do you plan to use your money from SYEP? [Check the TOP THREE] - Clothes , 33: How do you plan to use your money from SYEP? [Check the TOP THREE] - Food , 34: How do you plan to use your money from SYEP? [Check the TOP THREE] - Household expenses , 35: How do you plan to use your money from SYEP? [Check the TOP THREE] - Help support family , 36: How do you plan to use your money from SYEP? [Check the TOP THREE] - Electronics , 37: How do you plan to use your money from SYEP? [Check the TOP THREE] - Activities , 38: How do you plan to use your money from SYEP? [Check the TOP THREE] - Savings , 39: How do you plan to use your money from SYEP? [Check the TOP THREE] - Investments , 40: How do you plan to use your money from SYEP? [Check the TOP THREE] - School supplies, 41: How do you plan to use your money from SYEP? [Check the TOP THREE] - Other (please specify), 42: Have you been able to successfully log into the Hats & Ladders online orientation? , 43: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I used Hats & Ladders in a past year., 44: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I had the information that I needed to access Hats and Ladders., 45: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I am excited to use an online platform to improve my college and career readiness., 46: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I think Hats & Ladders is a valuable use of my time., 47: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - Hats & Ladders is user-friendly., 48: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I feel comfortable completing all the different parts of Hats & Ladders on my own., 49: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - Program staff provide the support I need to complete Hats & Ladders., 50: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I would like more group discussions about Hats & Ladders to help me build financial/career skills., 51: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I would like more conversations with the program staff to build on Hats & Ladders skills., 52: Did your SYEP provider conduct an orientation to the SYEP program in addition to Hats & Ladders?, 53: Please indicate how much you agree or disagree with the following statements about the orientation from your SYEP provider. - The orientation helped me to understand program expectations and goals, 54: Please indicate how much you agree or disagree with the following statements about the orientation from your SYEP provider. - The orientation provided guidance on how to complete required paperwork, 55: Please indicate how much you agree or disagree with the following statements about the orientation from your SYEP provider. - The orientation helped me feel ready for my summer work experience, 56: Which of the following have you EVER done as career preparation? [Check all that apply] - None of the above, 57: Which of the following have you EVER done as career preparation? [Check all that apply] - Prepared a resume , 58: Which of the following have you EVER done as career preparation? [Check all that apply] - Prepared a cover letter , 59: Which of the following have you EVER done as career preparation? [Check all that apply] - Reviewed a job application , 60: Which of the following have you EVER done as career preparation? [Check all that apply] - Searched for jobs online , 61: Which of the following have you EVER done as career preparation? [Check all that apply] - Learned how to apply for a job , 62: Which of the following have you EVER done as career preparation? [Check all that apply] - Developed answers to common interview questions , 63: Which of the following have you EVER done as career preparation? [Check all that apply] - Practiced my interview skills , 64: Which of the following have you EVER done as career preparation? [Check all that apply] - Asked an adult to serve as a reference , 65: Which of the following have you EVER done as career preparation? [Check all that apply] - Asked an adult for help finding a job , 66: Which of the following have you EVER done to manage your finances? [Check all that apply] - None of the above, 67: Which of the following have you EVER done to manage your finances? [Check all that apply] - Opened or used a bank account, 68: Which of the following have you EVER done to manage your finances? [Check all that apply] - Used direct deposit to receive payment, 69: Which of the following have you EVER done to manage your finances? [Check all that apply] - Received payment for employment, 70: Which of the following have you EVER done to manage your finances? [Check all that apply] - Saved money, 71: Which of the following have you EVER done to manage your finances? [Check all that apply] - Created a budget, 72: Which of the following have you EVER done to manage your finances? [Check all that apply] - Learned how to build credit, 73: Which of the following have you EVER done to manage your finances? [Check all that apply] - Learned how to protect my identity and avoid fraud, 74: Recipient - custom_value4, 75: Which of the following have you done in prior summers? [Check all that apply] - None of the above, 76: Which of the following have you done in prior summers? [Check all that apply] - SYEP with a job placement, 77: Which of the following have you done in prior summers? [Check all that apply] - SYEP with service learning , 78: Which of the following have you done in prior summers? [Check all that apply] - SYEP with project-based learning project , 79: Which of the following have you done in prior summers? [Check all that apply] - Summer job not through SYEP , 80: Which of the following have you done in prior summers? [Check all that apply] - Volunteered , 81: Which of the following have you done in prior summers? [Check all that apply] - Paid summer internship , 82: Which of the following have you done in prior summers? [Check all that apply] - Unpaid summer internship , 83: Which of the following have you done in prior summers? [Check all that apply] - Summer camp , 84: Which of the following have you done in prior summers? [Check all that apply] - Summer school, 85: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Volunteering, 86: What is the main reason you wanted to participate in SYEP? [Choose one answer], 87: What is the main reason you wanted to participate in SYEP? [Choose one answer] - Other (please specify), 88: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - The design of Hats & Ladders content is user-friendly and easy to manage., 89: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I feel comfortable completing parts of Hats & Ladders on my own (i.e., self-guided modules)., 90: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - Program staff provide the support I need to complete Hats & Ladders modules., 91: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I would like more group discussions about Hats & Ladders to support my skill building., 92: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I would like more live interaction with the program staff to supplement the Hats & Ladders modules., 93: Please indicate how much you agree or disagree with the following statements about the orientation from your SYEP provider. - The orientation provided guidance on how to effectively manage my time and progress through Hats & Ladders, 94: Which of the following have you EVER done? [Check all that apply] - None of the above - 78435018 - 625631731, 95: Which of the following have you EVER done? [Check all that apply] - Prepared a resume , 96: Which of the following have you EVER done? [Check all that apply] - Prepared a cover letter , 97: Which of the following have you EVER done? [Check all that apply] - Reviewed a job application , 98: Which of the following have you EVER done? [Check all that apply] - Searched for jobs online , 99: Which of the following have you EVER done? [Check all that apply] - Learned how to apply for a job , 100: Which of the following have you EVER done? [Check all that apply] - Developed answers to common interview questions , 101: Which of the following have you EVER done? [Check all that apply] - Practiced my interview skills , 102: Which of the following have you EVER done? [Check all that apply] - Asked an adult to serve as a reference , 103: Which of the following have you EVER done? [Check all that apply] - Asked an adult for help finding a job , 104: Which of the following have you EVER done? [Check all that apply] - None of the above - 78435019 - 624390237, 105: Which of the following have you EVER done? [Check all that apply] - Opened or used a bank account, 106: Which of the following have you EVER done? [Check all that apply] - Used direct deposit to receive payment, 107: Which of the following have you EVER done? [Check all that apply] - Received payment for employment, 108: Which of the following have you EVER done? [Check all that apply] - Saved money, 109: Which of the following have you EVER done? [Check all that apply] - Created a budget, 110: Which of the following have you EVER done? [Check all that apply] - Learned how to build credit, 111: Which of the following have you EVER done? [Check all that apply] - Learned how to protect my identity and avoid fraud, 112: Which of the following do you agree with? [Check all that apply] - None of the above, 113: Which of the following do you agree with? [Check all that apply] - I know how to resolve a conflict with a peer , 114: Which of the following do you agree with? [Check all that apply] - I have a lot to contribute to groups I belong to , 115: Which of the following do you agree with? [Check all that apply] - I know how to manage my emotions and temper , 116: Which of the following do you agree with? [Check all that apply] - I feel connected to people in my neighborhood , 117: Which of the following do you agree with? [Check all that apply] - I know how to ask for help when I need it, 118: Through which organization are you participating in the SYEP program? - Other/I don't know: (Please fill in), 119: Which of the following did you participate in with SYEP?[Check all that apply] - Work experience: In person, 120: Which of the following did you participate in with SYEP?[Check all that apply] - Work experience: Remote, 121: Which of the following did you participate in with SYEP?[Check all that apply] - Hats & Ladders, 122: Which of the following did you participate in with SYEP?[Check all that apply] - Another financial literacy curriculum, 123: Which of the following did you participate in with SYEP?[Check all that apply] - Professional and technical development (PTD) skills training (from my provider, CUNY, SUNY, Coursera, Microsoft, etc.), 124: Which of the following did you participate in with SYEP?[Check all that apply] - Tech Year or Tech:NYC, 125: Which of the following did you participate in with SYEP? [Check all that apply]  - In-person project-based learning, 126: Which of the following did you participate in with SYEP? [Check all that apply]  - Remote project-based learning, 127: Which of the following did you participate in with SYEP? [Check all that apply]  - Hats & Ladders, 128: Which of the following did you participate in with SYEP? [Check all that apply]  - Another financial literacy curriculum, 129: Which of the following did you participate in with SYEP? [Check all that apply]  - Professional and technical development (PTD) skills training (from my provider, CUNY, SUNY, Coursera, Microsoft, etc.), 130: Which of the following did you participate in with SYEP? [Check all that apply]  - Tech Year or Tech:NYC, 131: After taking the Hats & Ladders financial literacy training, how confident do you feel managing your money?, 132: Do you feel that a remote or in-person SYEP worksite experience would have better prepared you for your next job?, 133: Do you feel remote or in-person Project-Based Learning would have better prepared you for your next job?, 134: Please rate how strongly you agree with each statement about Tech Year/Tech:NYC - I can apply the content I am learning to my everyday life and career, 135: Please rate how strongly you agree with each statement about Tech Year/Tech:NYC - I felt prepared for each coming week during the program (I knew what workshops were happening and when they were, which Skillshare courses I should be completed, etc.), 136: Please rate how strongly you agree with each statement about Tech Year/Tech:NYC - I feel that I am on track (equipped with the skills and knowledge I need) to pursue a career in tech, 137: How interested were you in the tech sector... - Prior to starting Tech Year/Tech:NYC, 138: How interested were you in the tech sector... - Today/After completing Tech Year/Tech:NYC, 139: In which area or sector was most of your SYEP experience this summer? [Select one], 140: In which area or sector was most of your SYEP experience this summer? [Select one] - Other (please specify), 141: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Child care or Pre-school  , 142: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - K-12 Schools , 143: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Government agency , 144: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Civic engagement organization , 145: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Healthcare and mental health , 146: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Media and communications , 147: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Entertainment and sports , 148: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Social service , 149: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Real estate , 150: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Technology , 151: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Food and hospitality , 152: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Business and finance , 153: In which areas or sectors would you want your future SYEP work experiences to be? [Select

In [ ]:
df1['Participant.Unique.ID'] = df1['Participant.Unique.ID'].astype(str).str.strip()
df2['Participant.Unique.ID'] = df2['Participant.Unique.ID'].astype(str).str.strip()
df1['Year'] = df1['Year'].astype(int)
df2['Year'] = df2['Year'].astype(int)

In [ ]:
match_cols = ['Participant.Unique.ID', 'Year']
valid_combinations = df1.set_index(match_cols).index
filtered_df2 = df2[df2.set_index(match_cols).index.isin(valid_combinations)]

In [31]:
filtered_df2.shape

(17764, 636)

In [32]:
filtered_df2.to_csv('data/to_use/surveys.csv', index=False)

survey clean

In [4]:
import pandas as pd

In [5]:
%cd "/Users/Sonia/Documents/SYEP"

df = pd.read_csv('data/to_use/surveys.csv')

/Applications/Positron.app/Contents/Resources/app/extensions/positron-python/python_files/lib/ipykernel/py3/IPython/core/magics/osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

/Users/sonia/Documents/SYEP

<positron-console-cell-5>:3: DtypeWarning: Columns (0: Through which organization are you participating in the SYEP program? - Other/I don't know: (Please fill in), 1: How old are you?, 2: How did you hear about this SYEP program? [Choose one answer], 3: How did you hear about this SYEP program? [Choose one answer] - Other (please specify), 4: What would you have done this summer if you had not been in SYEP? [Check all that apply] - None of the above, 5: What would you have done this summer if you had not been in SYEP? [Check all that apply] - A different part-time job, 6: What would you have done this summer if you had not been in SYEP? [Check all that apply] - A different full-time job, 7: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Volunteered, 8: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Paid summer internship, 9: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Unpaid summer internship, 10: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Summer camp, 11: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Summer school, 12: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Spending time with friends, 13: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Spending time with family, 14: What would you have done this summer if you had not been in SYEP? [Check all that apply] - I had no other summer plans, 15: Please indicate which of the following statements you agree with. [Check all that apply] - None of the above, 16: Please indicate which of the following statements you agree with. [Check all that apply] - SYEP was my first choice for a summer program this year , 17: Please indicate which of the following statements you agree with. [Check all that apply] - I understood all the steps I needed to complete to apply and enroll to the program , 18: Please indicate which of the following statements you agree with. [Check all that apply] - I was able to get the information I needed to apply quickly and easily , 19: Please indicate which of the following statements you agree with. [Check all that apply] - When I started this program, I had a good idea of what it would be like , 20: Please indicate which of the following statements you agree with. [Check all that apply] - I understand how to earn the full payment amount, 21: Please indicate which of the following statements you agree with. [Check all that apply] - I understand the steps I need to take to receive my payment , 22: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Learn more about career options, 23: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Earn money, 24: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Meet new people while participating in the programming, 25: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Find a summer job or internship, 26: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Learn new skills, 27: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Receive work readiness training, 28: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Have safe and productive activity this summer, 29: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - To earn course credit, 30: Besides earning money, what were other top reasons you wanted to participate in SYEP? [Check up to THREE responses] - Other (please specify), 31: How do you plan to use your money from SYEP? [Check the TOP THREE] - Clothes , 32: How do you plan to use your money from SYEP? [Check the TOP THREE] - Food , 33: How do you plan to use your money from SYEP? [Check the TOP THREE] - Household expenses , 34: How do you plan to use your money from SYEP? [Check the TOP THREE] - Help support family , 35: How do you plan to use your money from SYEP? [Check the TOP THREE] - Electronics , 36: How do you plan to use your money from SYEP? [Check the TOP THREE] - Activities , 37: How do you plan to use your money from SYEP? [Check the TOP THREE] - Savings , 38: How do you plan to use your money from SYEP? [Check the TOP THREE] - Investments , 39: How do you plan to use your money from SYEP? [Check the TOP THREE] - School supplies, 40: How do you plan to use your money from SYEP? [Check the TOP THREE] - Other (please specify), 41: Have you been able to successfully log into the Hats & Ladders online orientation? , 42: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I used Hats & Ladders in a past year., 43: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I had the information that I needed to access Hats and Ladders., 44: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I am excited to use an online platform to improve my college and career readiness., 45: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I think Hats & Ladders is a valuable use of my time., 46: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - Hats & Ladders is user-friendly., 47: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I feel comfortable completing all the different parts of Hats & Ladders on my own., 48: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - Program staff provide the support I need to complete Hats & Ladders., 49: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I would like more group discussions about Hats & Ladders to help me build financial/career skills., 50: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I would like more conversations with the program staff to build on Hats & Ladders skills., 51: Did your SYEP provider conduct an orientation to the SYEP program in addition to Hats & Ladders?, 52: Please indicate how much you agree or disagree with the following statements about the orientation from your SYEP provider. - The orientation helped me to understand program expectations and goals, 53: Please indicate how much you agree or disagree with the following statements about the orientation from your SYEP provider. - The orientation provided guidance on how to complete required paperwork, 54: Please indicate how much you agree or disagree with the following statements about the orientation from your SYEP provider. - The orientation helped me feel ready for my summer work experience, 55: Which of the following have you EVER done as career preparation? [Check all that apply] - None of the above, 56: Which of the following have you EVER done as career preparation? [Check all that apply] - Prepared a resume , 57: Which of the following have you EVER done as career preparation? [Check all that apply] - Prepared a cover letter , 58: Which of the following have you EVER done as career preparation? [Check all that apply] - Reviewed a job application , 59: Which of the following have you EVER done as career preparation? [Check all that apply] - Searched for jobs online , 60: Which of the following have you EVER done as career preparation? [Check all that apply] - Learned how to apply for a job , 61: Which of the following have you EVER done as career preparation? [Check all that apply] - Developed answers to common interview questions , 62: Which of the following have you EVER done as career preparation? [Check all that apply] - Practiced my interview skills , 63: Which of the following have you EVER done as career preparation? [Check all that apply] - Asked an adult to serve as a reference , 64: Which of the following have you EVER done as career preparation? [Check all that apply] - Asked an adult for help finding a job , 65: Which of the following have you EVER done to manage your finances? [Check all that apply] - None of the above, 66: Which of the following have you EVER done to manage your finances? [Check all that apply] - Opened or used a bank account, 67: Which of the following have you EVER done to manage your finances? [Check all that apply] - Used direct deposit to receive payment, 68: Which of the following have you EVER done to manage your finances? [Check all that apply] - Received payment for employment, 69: Which of the following have you EVER done to manage your finances? [Check all that apply] - Saved money, 70: Which of the following have you EVER done to manage your finances? [Check all that apply] - Created a budget, 71: Which of the following have you EVER done to manage your finances? [Check all that apply] - Learned how to build credit, 72: Which of the following have you EVER done to manage your finances? [Check all that apply] - Learned how to protect my identity and avoid fraud, 73: Which of the following have you done in prior summers? [Check all that apply] - None of the above, 74: Which of the following have you done in prior summers? [Check all that apply] - SYEP with a job placement, 75: Which of the following have you done in prior summers? [Check all that apply] - SYEP with service learning , 76: Which of the following have you done in prior summers? [Check all that apply] - SYEP with project-based learning project , 77: Which of the following have you done in prior summers? [Check all that apply] - Summer job not through SYEP , 78: Which of the following have you done in prior summers? [Check all that apply] - Volunteered , 79: Which of the following have you done in prior summers? [Check all that apply] - Paid summer internship , 80: Which of the following have you done in prior summers? [Check all that apply] - Unpaid summer internship , 81: Which of the following have you done in prior summers? [Check all that apply] - Summer camp , 82: Which of the following have you done in prior summers? [Check all that apply] - Summer school, 83: What would you have done this summer if you had not been in SYEP? [Check all that apply] - Volunteering, 84: What is the main reason you wanted to participate in SYEP? [Choose one answer], 85: What is the main reason you wanted to participate in SYEP? [Choose one answer] - Other (please specify), 86: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - The design of Hats & Ladders content is user-friendly and easy to manage., 87: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I feel comfortable completing parts of Hats & Ladders on my own (i.e., self-guided modules)., 88: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - Program staff provide the support I need to complete Hats & Ladders modules., 89: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I would like more group discussions about Hats & Ladders to support my skill building., 90: Please indicate how much you agree or disagree with the following statements regarding the Hats & Ladders online orientation program - I would like more live interaction with the program staff to supplement the Hats & Ladders modules., 91: Please indicate how much you agree or disagree with the following statements about the orientation from your SYEP provider. - The orientation provided guidance on how to effectively manage my time and progress through Hats & Ladders, 92: Which of the following have you EVER done? [Check all that apply] - None of the above - 78435018 - 625631731, 93: Which of the following have you EVER done? [Check all that apply] - Prepared a resume , 94: Which of the following have you EVER done? [Check all that apply] - Prepared a cover letter , 95: Which of the following have you EVER done? [Check all that apply] - Reviewed a job application , 96: Which of the following have you EVER done? [Check all that apply] - Searched for jobs online , 97: Which of the following have you EVER done? [Check all that apply] - Learned how to apply for a job , 98: Which of the following have you EVER done? [Check all that apply] - Developed answers to common interview questions , 99: Which of the following have you EVER done? [Check all that apply] - Practiced my interview skills , 100: Which of the following have you EVER done? [Check all that apply] - Asked an adult to serve as a reference , 101: Which of the following have you EVER done? [Check all that apply] - Asked an adult for help finding a job , 102: Which of the following have you EVER done? [Check all that apply] - None of the above - 78435019 - 624390237, 103: Which of the following have you EVER done? [Check all that apply] - Opened or used a bank account, 104: Which of the following have you EVER done? [Check all that apply] - Used direct deposit to receive payment, 105: Which of the following have you EVER done? [Check all that apply] - Received payment for employment, 106: Which of the following have you EVER done? [Check all that apply] - Saved money, 107: Which of the following have you EVER done? [Check all that apply] - Created a budget, 108: Which of the following have you EVER done? [Check all that apply] - Learned how to build credit, 109: Which of the following have you EVER done? [Check all that apply] - Learned how to protect my identity and avoid fraud, 110: Which of the following do you agree with? [Check all that apply] - None of the above, 111: Which of the following do you agree with? [Check all that apply] - I know how to resolve a conflict with a peer , 112: Which of the following do you agree with? [Check all that apply] - I have a lot to contribute to groups I belong to , 113: Which of the following do you agree with? [Check all that apply] - I know how to manage my emotions and temper , 114: Which of the following do you agree with? [Check all that apply] - I feel connected to people in my neighborhood , 115: Which of the following do you agree with? [Check all that apply] - I know how to ask for help when I need it, 116: Through which organization are you participating in the SYEP program? - Other/I don't know: (Please fill in), 117: Which of the following did you participate in with SYEP?[Check all that apply] - Work experience: In person, 118: Which of the following did you participate in with SYEP?[Check all that apply] - Work experience: Remote, 119: Which of the following did you participate in with SYEP?[Check all that apply] - Hats & Ladders, 120: Which of the following did you participate in with SYEP?[Check all that apply] - Another financial literacy curriculum, 121: Which of the following did you participate in with SYEP?[Check all that apply] - Professional and technical development (PTD) skills training (from my provider, CUNY, SUNY, Coursera, Microsoft, etc.), 122: Which of the following did you participate in with SYEP?[Check all that apply] - Tech Year or Tech:NYC, 123: Which of the following did you participate in with SYEP? [Check all that apply]  - In-person project-based learning, 124: Which of the following did you participate in with SYEP? [Check all that apply]  - Remote project-based learning, 125: Which of the following did you participate in with SYEP? [Check all that apply]  - Hats & Ladders, 126: Which of the following did you participate in with SYEP? [Check all that apply]  - Another financial literacy curriculum, 127: Which of the following did you participate in with SYEP? [Check all that apply]  - Professional and technical development (PTD) skills training (from my provider, CUNY, SUNY, Coursera, Microsoft, etc.), 128: Which of the following did you participate in with SYEP? [Check all that apply]  - Tech Year or Tech:NYC, 129: After taking the Hats & Ladders financial literacy training, how confident do you feel managing your money?, 130: Do you feel that a remote or in-person SYEP worksite experience would have better prepared you for your next job?, 131: Please rate how strongly you agree with each statement about Tech Year/Tech:NYC - I can apply the content I am learning to my everyday life and career, 132: Please rate how strongly you agree with each statement about Tech Year/Tech:NYC - I felt prepared for each coming week during the program (I knew what workshops were happening and when they were, which Skillshare courses I should be completed, etc.), 133: Please rate how strongly you agree with each statement about Tech Year/Tech:NYC - I feel that I am on track (equipped with the skills and knowledge I need) to pursue a career in tech, 134: How interested were you in the tech sector... - Prior to starting Tech Year/Tech:NYC, 135: How interested were you in the tech sector... - Today/After completing Tech Year/Tech:NYC, 136: In which area or sector was most of your SYEP experience this summer? [Select one], 137: In which area or sector was most of your SYEP experience this summer? [Select one] - Other (please specify), 138: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Child care or Pre-school  , 139: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - K-12 Schools , 140: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Government agency , 141: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Civic engagement organization , 142: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Healthcare and mental health , 143: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Media and communications , 144: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Entertainment and sports , 145: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Social service , 146: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Real estate , 147: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Technology , 148: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Food and hospitality , 149: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Business and finance , 150: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Retail sales and marketing , 151: In which areas or sectors would you want your future SYEP work experiences to be? [Select up to 5] - Transportation , 152: In which areas or sectors would you want your futur

In [6]:
df['SurveyType'] = df['SurveyType'].str.extract(r"^(PRE|POST)") # remove years -> now 2 unique values, PRE or POST

In [7]:
df[df['SurveyType'] == 'PRE'].isna().mean() * 100

Through which organization are you participating in the SYEP program?                                            12.463409
Through which organization are you participating in the SYEP program? - Other/I don't know: (Please fill in)     87.547850
How old are you?                                                                                                  0.000000
In which borough is your school located?                                                                          0.000000
How did you hear about this SYEP program? [Choose one answer]                                                     1.925242
                                                                                                                   ...
Have your career goals changed because of your SYEP experience?                                                 100.000000
Which of the following do you plan to do in the next year? (Select all that apply)                              100.000000
How confident are you in your ability to achieve your career goals?                                             100.000000
Participant.Unique.ID                                                                                             0.000000
Year                                                                                                              0.000000
Length: 636, dtype: float64

In [8]:
df[df['SurveyType'] == 'POST'].isna().mean() * 100

Through which organization are you participating in the SYEP program?                                            10.752083
Through which organization are you participating in the SYEP program? - Other/I don't know: (Please fill in)    100.000000
How old are you?                                                                                                  0.000000
In which borough is your school located?                                                                          0.000000
How did you hear about this SYEP program? [Choose one answer]                                                   100.000000
                                                                                                                   ...
Have your career goals changed because of your SYEP experience?                                                  79.790588
Which of the following do you plan to do in the next year? (Select all that apply)                               79.734294
How confident are you in your ability to achieve your career goals?                                              79.756812
Participant.Unique.ID                                                                                             0.000000
Year                                                                                                              0.000000
Length: 636, dtype: float64

In [59]:
from utils.survey_blocks import BlockSpec, build_block_frame, audit_block, discover_items

CF = BlockSpec(
    prefix="cf",
    stem="What would you have done this summer if you had not been in SYEP? [Check all that apply]",
    nota_label="None of the above",
    groups={
        "paid_alternative": ["A different part-time job",
                                "A different full-time job",
                                "Paid summer internship"],
        "unpaid_activity":  ["Volunteered", "Unpaid summer internship",
                                 "Summer camp", "Summer school"],
    },
    singles={"no_plans": "I had no other summer plans"},
    exclude_from_count=["I had no other summer plans"],
)

audit_block(df, CF)

[cf] block presence by Year:
Year
2022    0.5
2023    0.5
2024    0.5
2025    0.5

,prefix,label,column,n_nonnull,n_selected,n_uncoercible,example_bad
0,cf,None of the above,What would you have done this summer if you ha...,8882,260,0,None
1,cf,A different part-time job,What would you have done this summer if you ha...,8882,4039,0,None
2,cf,A different full-time job,What would you have done this summer if you ha...,8882,1631,0,None
3,cf,Volunteered,What would you have done this summer if you ha...,6350,1313,0,None
4,cf,Paid summer internship,What would you have done this summer if you ha...,8882,1750,0,None
5,cf,Unpaid summer internship,What would you have done this summer if you ha...,8882,579,0,None
6,cf,Summer camp,What would you have done this summer if you ha...,8882,593,0,None
7,cf,Summer school,What would you have done this summer if you ha...,8882,663,0,None
8,cf,Spending time with friends,What would you have done this summer if you ha...,8882,3903,0,None
9,cf,Spending time with family,What would you have done this summer if you ha...,8882,4337,0,None
10,cf,I had no other summer plans,What would you have done this summer if you ha...,8882,1404,0,None
11,cf,Volunteering,What would you have done this summer if you ha...,2532,516,0,None

In [65]:
EXPECTATIONS = BlockSpec(
    prefix="expect",
    stem="Please indicate which of the following statements you agree with. [Check all that apply]",
    groups={
        "app_clarity": [
            "I understood all the steps I needed to complete to apply and enroll to the program",
            "I was able to get the information I needed to apply quickly and easily",
        ],
    },
    singles={
        "first_choice": "SYEP was my first choice for a summer program this year",
        "knew_what_to_expect": "When I started this program, I had a good idea of what it would be like",
    },
)

audit_block(df, EXPECTATIONS)

[expect] block presence by Year:
Year
2022    0.5
2023    0.5
2024    0.5
2025    0.5

,prefix,label,column,n_nonnull,n_selected,n_uncoercible,example_bad
0,expect,None of the above,Please indicate which of the following stateme...,8882,183,0,None
1,expect,SYEP was my first choice for a summer program ...,Please indicate which of the following stateme...,8882,7079,0,None
2,expect,I understood all the steps I needed to complet...,Please indicate which of the following stateme...,8882,6749,0,None
3,expect,I was able to get the information I needed to ...,Please indicate which of the following stateme...,8882,5663,0,None
4,expect,"When I started this program, I had a good idea...",Please indicate which of the following stateme...,8882,4377,0,None
5,expect,I understand how to earn the full payment amount,Please indicate which of the following stateme...,8882,5380,0,None
6,expect,I understand the steps I need to take to recei...,Please indicate which of the following stateme...,8882,5747,0,None

In [73]:
BENEFITS = BlockSpec(
    prefix="benefit",
    stem="Besides earning money, what were the five biggest benefits you received from SYEP this past summer? [Select up to 5]",
    groups={
        "career_clarity": ["Identified careers I am interested in",
                           "Developed a career plan with clear next steps"],
        "job_readiness": ["Understood how to look for and get a job",
                          "Understood what employers are looking for",
                          "Developed a resume or other job application materials",
                          "Understood how to interact with professionals"],
        "self_efficacy": ["Developed new skills",
                          "Understood my own strengths",
                          "Felt motivated to seek a job"],
        "academic_credit": ["Earned course credit", "Earned academic credit"],
    },
    singles={"mentor_relationship": "Developed relationships with mentors/supervisors",
             "money_management": "Understood money management"},
    exclude_from_count=["Other (please specify)", "Decided to go to college"],
)

In [74]:
audit_block(df, BENEFITS)

[benefit] block presence by Year:
Year
2022    0.5
2023    0.5
2024    0.5
2025    0.5

,prefix,label,column,n_nonnull,n_selected,n_uncoercible,example_bad
0,benefit,Developed new skills,"Besides earning money, what were the five bigg...",8882,4705,0,NaN
1,benefit,Understood how to look for and get a job,"Besides earning money, what were the five bigg...",8882,3420,0,NaN
2,benefit,Understood what employers are looking for,"Besides earning money, what were the five bigg...",8882,3497,0,NaN
3,benefit,Developed a resume or other job application ma...,"Besides earning money, what were the five bigg...",8882,2275,0,NaN
4,benefit,Identified careers I am interested in,"Besides earning money, what were the five bigg...",8882,2960,0,NaN
5,benefit,Developed a career plan with clear next steps,"Besides earning money, what were the five bigg...",8882,1621,0,NaN
6,benefit,Understood my own strengths,"Besides earning money, what were the five bigg...",8882,3789,0,NaN
7,benefit,Felt motivated to seek a job,"Besides earning money, what were the five bigg...",8882,2887,0,NaN
8,benefit,Earned course credit,"Besides earning money, what were the five bigg...",2532,42,0,NaN
9,benefit,Decided to go to college,"Besides earning money, what were the five bigg...",2532,128,0,NaN
10,benefit,Made plans to enroll in a college or training ...,"Besides earning money, what were the five bigg...",8882,419,0,NaN
11,benefit,Understood how to interact with professionals,"Besides earning money, what were the five bigg...",8882,4085,0,NaN
12,benefit,Developed relationships with mentors/supervisors,"Besides earning money, what were the five bigg...",8882,3034,0,NaN
13,benefit,Understood money management,"Besides earning money, what were the five bigg...",8882,2736,0,NaN
14,benefit,Other (please specify),"Besides earning money, what were the five bigg...",195,2,191,Didn’t really
15,benefit,Earned academic credit,"Besides earning money, what were the five bigg...",6350,177,0,NaN

In [12]:
from utils.build_survey_features import build_wide, report

wide = build_wide(df, include_secondary=False, how="inner")
report(wide)

Block coverage before split:
                  cf  expect  benefit
Year SurveyType
2022 POST        0.0     0.0      1.0
     PRE         1.0     1.0      0.0
2023 POST        0.0     0.0      1.0
     PRE         1.0     1.0      0.0
2024 POST        0.0     0.0      1.0
     PRE         1.0     1.0      0.0
2025 POST        0.0     0.0      1.0
     PRE         1.0     1.0      0.0

dropped low-variance indicators: ['expect_nota', 'cf_nota', 'benefit_academic_credit']

rows: 8,882   unique people: 8,209
  ! 673 repeated people. Rows are NOT independent --
    cluster SEs on Participant.Unique.ID, or keep first year only.

rows per year:
Year
2022    2532
2023    1828
2024    2718
2025    1804

wave coverage:
wave_coverage
both          8882
left_only        0
right_only       0
  note: all rows matched -- input was already pruned to pairs,
        so no attrition comparison is possible from this frame.

feature coverage (want ~1.0 for in-scope features):
benefit_money_management       0.984
benefit_self_efficacy          0.984
benefit_job_readiness          0.984
benefit_career_clarity         0.984
benefit_n_selected             0.984
benefit_mentor_relationship    0.984
benefit_answered               1.000
expect_knew_what_to_expect     1.000
expect_first_choice            1.000
cf_answered                    1.000
expect_answered                1.000
cf_no_plans                    1.000
cf_leisure_only                1.000
cf_unpaid_activity             1.000
cf_paid_alternative            1.000
cf_n_selected                  1.000
expect_n_selected              1.000
expect_app_clarity             1.000

binary endorsement rates:
cf_no_plans                    0.158
cf_unpaid_activity             0.284
benefit_money_management       0.313
benefit_mentor_relationship    0.347
benefit_career_clarity         0.430
expect_knew_what_to_expect     0.493
cf_leisure_only                0.560
cf_paid_alternative            0.606
expect_first_choice            0.797
expect_app_clarity             0.799
benefit_self_efficacy          0.802
benefit_job_readiness          0.831
benefit_answered               0.984
cf_answered                    1.000
expect_answered                1.000

In [15]:
wide.to_csv("data/to_use/survey_features_wide.csv", index=False)